const body = document.getElementsByTagName("body")[0];
const mySection = document.createElement("section");
mySection.classList.add("tile-game");
const myDiv1 = document.createElement("div");
myDiv1.classList.add("tile")
const myImg11 = document.createElement("img")
myImg11.classList.add("front")
myImg11.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg11.setAttribute("alt", "BMW")
myDiv1.appendChild(myImg11)
const myImg12 = document.createElement("img")
myImg12.classList.add("back")
myImg12.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg12.setAttribute("alt", "Flip It")
myDiv1.appendChild(myImg12)
const myDiv2 = document.createElement("div")
myDiv2.classList.add("tile")
const myImg21 = document.createElement("img")
myImg21.classList.add("front")
myImg21.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg21.setAttribute("alt", "Audi")
myDiv2.appendChild(myImg21)
const myImg22 = document.createElement("img")
myImg22.classList.add("back")
myImg22.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg22.setAttribute("alt", "Audi")
myDiv2.appendChild(myImg22)
const myDiv3 = document.createElement("div")
myDiv3.classList.add("tile")
const myImg31 = document.createElement("img")
myImg31.classList.add("front")
myImg31.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg31.setAttribute("alt", "Audi")
myDiv3.appendChild(myImg31)
const myImg32 = document.createElement("img")
myImg32.classList.add("back")
myImg32.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg32.setAttribute("alt", "Audi")
myDiv3.appendChild(myImg32)
const myDiv4 = document.createElement("div")
myDiv4.classList.add("tile")
const myImg41 = document.createElement("img")
myImg41.classList.add("front")
myImg41.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg41.setAttribute("alt", "Audi")
myDiv4.appendChild(myImg41)
const myImg42 = document.createElement("img")
myImg42.classList.add("back")
myImg42.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg42.setAttribute("alt", "Audi")
myDiv4.appendChild(myImg42)
const myDiv5 = document.createElement("div")
myDiv5.classList.add("tile")
const myImg51 = document.createElement("img")
myImg51.classList.add("front")
myImg51.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg51.setAttribute("alt", "Audi")
myDiv5.appendChild(myImg51)
const myImg52 = document.createElement("img")
myImg52.classList.add("back")
myImg52.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg52.setAttribute("alt", "Audi")
myDiv5.appendChild(myImg52)
const myDiv6 = document.createElement("div")
myDiv6.classList.add("tile")
const myImg61 = document.createElement("img")
myImg61.classList.add("front")
myImg61.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg61.setAttribute("alt", "Audi")
myDiv6.appendChild(myImg61)
const myImg62 = document.createElement("img")
myImg62.classList.add("back")
myImg62.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg62.setAttribute("alt", "Audi")
myDiv6.appendChild(myImg62)
const myDiv7 = document.createElement("div")
myDiv7.classList.add("tile")
const myImg71 = document.createElement("img")
myImg71.classList.add("front")
myImg71.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg71.setAttribute("alt", "Audi")
myDiv7.appendChild(myImg71)
const myImg72 = document.createElement("img")
myImg72.classList.add("back")
myImg72.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg72.setAttribute("alt", "Audi")
myDiv7.appendChild(myImg72)
const myDiv8 = document.createElement("div")
myDiv8.classList.add("tile")
const myImg81 = document.createElement("img")
myImg81.classList.add("front")
myImg81.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg81.setAttribute("alt", "Audi")
myDiv8.appendChild(myImg81)
const myImg82 = document.createElement("img")
myImg82.classList.add("back")
myImg82.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg82.setAttribute("alt", "Audi")
myDiv8.appendChild(myImg82)
const myDiv9 = document.createElement("div")
myDiv9.classList.add("tile")
const myImg91 = document.createElement("img")
myImg91.classList.add("front")
myImg91.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg91.setAttribute("alt", "Audi")
myDiv9.appendChild(myImg91)
const myImg92 = document.createElement("img")
myImg92.classList.add("back")
myImg92.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg92.setAttribute("alt", "Audi")
myDiv9.appendChild(myImg92)
const myDiv10 = document.createElement("div")
myDiv10.classList.add("tile")
const myImg101 = document.createElement("img")
myImg101.classList.add("front")
myImg101.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg101.setAttribute("alt", "Audi")
myDiv10.appendChild(myImg101)
const myImg102 = document.createElement("img")
myImg102.classList.add("back")
myImg102.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg102.setAttribute("alt", "Audi")
myDiv10.appendChild(myImg102)
const myDiv11 = document.createElement("div")
myDiv11.classList.add("tile")
const myImg111 = document.createElement("img")
myImg111.classList.add("front")
myImg111.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg111.setAttribute("alt", "Audi")
myDiv11.appendChild(myImg111)
const myImg112 = document.createElement("img")
myImg112.classList.add("back")
myImg112.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg112.setAttribute("alt", "Audi")
myDiv11.appendChild(myImg112)
const myDiv12 = document.createElement("div")
myDiv12.classList.add("tile")
const myImg121 = document.createElement("img")
myImg121.classList.add("front")
myImg121.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg121.setAttribute("alt", "Audi")
myDiv12.appendChild(myImg121)
const myImg122 = document.createElement("img")
myImg122.classList.add("back")
myImg122.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg122.setAttribute("alt", "Audi")
myDiv12.appendChild(myImg122)
const myDiv13 = document.createElement("div")
myDiv13.classList.add("tile")
const myImg131 = document.createElement("img")
myImg131.classList.add("front")
myImg131.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg131.setAttribute("alt", "Audi")
myDiv13.appendChild(myImg131)
const myImg132 = document.createElement("img")
myImg132.classList.add("back")
myImg132.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg132.setAttribute("alt", "Audi")
myDiv13.appendChild(myImg132)
const myDiv14 = document.createElement("div")
myDiv14.classList.add("tile")
const myImg141 = document.createElement("img")
myImg141.classList.add("front")
myImg141.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg141.setAttribute("alt", "Audi")
myDiv14.appendChild(myImg141)
const myImg142 = document.createElement("img")
myImg142.classList.add("back")
myImg142.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg142.setAttribute("alt", "Audi")
myDiv14.appendChild(myImg142)
const myDiv15 = document.createElement("div")
myDiv15.classList.add("tile")
const myImg151 = document.createElement("img")
myImg151.classList.add("front")
myImg151.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg151.setAttribute("alt", "Audi")
myDiv15.appendChild(myImg151)
const myImg152 = document.createElement("img")
myImg152.classList.add("back")
myImg152.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg152.setAttribute("alt", "Audi")
myDiv15.appendChild(myImg152)
const myDiv16 = document.createElement("div")
myDiv16.classList.add("tile")
const myImg161 = document.createElement("img")
myImg161.classList.add("front")
myImg161.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg161.setAttribute("alt", "Audi")
myDiv16.appendChild(myImg161)
const myImg162 = document.createElement("img")
myImg162.classList.add("back")
myImg162.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg162.setAttribute("alt", "Audi")
myDiv16.appendChild(myImg162)
const myDiv17 = document.createElement("div")
myDiv17.classList.add("tile")
const myImg171 = document.createElement("img")
myImg171.classList.add("front")
myImg171.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg171.setAttribute("alt", "Audi")
myDiv17.appendChild(myImg171)
const myImg172 = document.createElement("img")
myImg172.classList.add("back")
myImg172.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg172.setAttribute("alt", "Audi")
myDiv17.appendChild(myImg172)
const myDiv18 = document.createElement("div")
myDiv18.classList.add("tile")
const myImg181 = document.createElement("img")
myImg181.classList.add("front")
myImg181.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg181.setAttribute("alt", "Audi")
myDiv18.appendChild(myImg181)
const myImg182 = document.createElement("img")
myImg182.classList.add("back")
myImg182.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg182.setAttribute("alt", "Audi")
myDiv18.appendChild(myImg182)
const myDiv19 = document.createElement("div")
myDiv19.classList.add("tile")
const myImg191 = document.createElement("img")
myImg191.classList.add("front")
myImg191.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg191.setAttribute("alt", "Audi")
myDiv19.appendChild(myImg191)
const myImg192 = document.createElement("img")
myImg192.classList.add("back")
myImg192.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg192.setAttribute("alt", "Audi")
myDiv19.appendChild(myImg192)
const myDiv20 = document.createElement("div")
myDiv20.classList.add("tile")
const myImg201 = document.createElement("img")
myImg201.classList.add("front")
myImg201.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg201.setAttribute("alt", "Audi")
myDiv20.appendChild(myImg201)
const myImg202 = document.createElement("img")
myImg202.classList.add("back")
myImg202.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg202.setAttribute("alt", "Audi")
myDiv20.appendChild(myImg202)
const myDiv21 = document.createElement("div")
myDiv21.classList.add("tile")
const myImg211 = document.createElement("img")
myImg211.classList.add("front")
myImg211.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg211.setAttribute("alt", "Audi")
myDiv21.appendChild(myImg211)
const myImg212 = document.createElement("img")
myImg212.classList.add("back")
myImg212.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg212.setAttribute("alt", "Audi")
myDiv21.appendChild(myImg212)
const myDiv22 = document.createElement("div")
myDiv22.classList.add("tile")
const myImg221 = document.createElement("img")
myImg221.classList.add("front")
myImg221.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg221.setAttribute("alt", "Audi")
myDiv22.appendChild(myImg221)
const myImg222 = document.createElement("img")
myImg222.classList.add("back")
myImg222.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg222.setAttribute("alt", "Audi")
myDiv22.appendChild(myImg222)
const myDiv23 = document.createElement("div")
myDiv23.classList.add("tile")
const myImg231 = document.createElement("img")
myImg231.classList.add("front")
myImg231.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg231.setAttribute("alt", "Audi")
myDiv23.appendChild(myImg231)
const myImg232 = document.createElement("img")
myImg232.classList.add("back")
myImg232.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg232.setAttribute("alt", "Audi")
myDiv23.appendChild(myImg232)
const myDiv24 = document.createElement("div")
myDiv24.classList.add("tile")
const myImg241 = document.createElement("img")
myImg241.classList.add("front")
myImg241.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg241.setAttribute("alt", "Audi")
myDiv24.appendChild(myImg241)
const myImg242 = document.createElement("img")
myImg242.classList.add("back")
myImg242.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg242.setAttribute("alt", "Audi")
myDiv24.appendChild(myImg242)
const myDiv25 = document.createElement("div")
myDiv25.classList.add("tile")
const myImg251 = document.createElement("img")
myImg251.classList.add("front")
myImg251.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg251.setAttribute("alt", "Audi")
myDiv25.appendChild(myImg251)
const myImg252 = document.createElement("img")
myImg252.classList.add("back")
myImg252.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg252.setAttribute("alt", "Audi")
myDiv25.appendChild(myImg252)
const myDiv26 = document.createElement("div")
myDiv26.classList.add("tile")
const myImg261 = document.createElement("img")
myImg261.classList.add("front")
myImg261.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg261.setAttribute("alt", "Audi")
myDiv26.appendChild(myImg261)
const myImg262 = document.createElement("img")
myImg262.classList.add("back")
myImg262.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg262.setAttribute("alt", "Audi")
myDiv26.appendChild(myImg262)
const myDiv27 = document.createElement("div")
myDiv27.classList.add("tile")
const myImg271 = document.createElement("img")
myImg271.classList.add("front")
myImg271.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg271.setAttribute("alt", "Audi")
myDiv27.appendChild(myImg271)
const myImg272 = document.createElement("img")
myImg272.classList.add("back")
myImg272.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg272.setAttribute("alt", "Audi")
myDiv27.appendChild(myImg272)
const myDiv28 = document.createElement("div")
myDiv28.classList.add("tile")
const myImg281 = document.createElement("img")
myImg281.classList.add("front")
myImg281.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg281.setAttribute("alt", "Audi")
myDiv28.appendChild(myImg281)
const myImg282 = document.createElement("img")
myImg282.classList.add("back")
myImg282.setAttribute("src", "https://www.underconsideration.com/brandnew/archives/bmw_2020_logo_white.png")
myImg282.setAttribute("alt", "Audi")
myDiv28.appendChild(myImg282)

mySection.appendChild(myDiv1)
mySection.appendChild(myDiv2)
mySection.appendChild(myDiv3)
mySection.appendChild(myDiv4)
mySection.appendChild(myDiv5)
mySection.appendChild(myDiv6)
mySection.appendChild(myDiv7)
mySection.appendChild(myDiv8)
mySection.appendChild(myDiv9)
mySection.appendChild(myDiv10)
mySection.appendChild(myDiv11)
mySection.appendChild(myDiv12)
mySection.appendChild(myDiv13)
mySection.appendChild(myDiv14)
mySection.appendChild(myDiv15)
mySection.appendChild(myDiv16)
mySection.appendChild(myDiv17)
mySection.appendChild(myDiv18)
mySection.appendChild(myDiv19)
mySection.appendChild(myDiv20)
mySection.appendChild(myDiv21)
mySection.appendChild(myDiv22)
mySection.appendChild(myDiv23)
mySection.appendChild(myDiv24)
mySection.appendChild(myDiv25)
mySection.appendChild(myDiv26)
mySection.appendChild(myDiv27)
mySection.appendChild(myDiv28)
body.appendChild(mySection);

const cards = document.querySelectorAll('.tile');

let isFlipped = false;
let locked = false;
let firstTile, secondTile;

function flip() {
  if (locked) return;
  if (this === firstTile) return;

  this.classList.add('flip');

  if (!isFlipped) {
    isFlipped = true;
    firstTile = this;
    return;
  }
  secondTile = this;
  checkForMatch();
}
