const body = document.getElementsByTagName("body")[0];
const myButton = document.createElement('button')
var node = document.createTextNode("Start");
myButton.appendChild(node);
body.appendChild(myButton)
const mySection = document.createElement("section");
mySection.classList.add("tile-game");
const myDiv1 = document.createElement("div");
myDiv1.classList.add("tile")
myDiv1.setAttribute("data-name", "BMW")
const myImg11 = document.createElement("img")
myImg11.classList.add("front")
myImg11.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/bmw-logo1.jpg")
myImg11.setAttribute("alt", "BMW")
myDiv1.appendChild(myImg11)
const myImg12 = document.createElement("img")
myImg12.classList.add("back")
myImg12.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg12.setAttribute("alt", "Flip It")
myDiv1.appendChild(myImg12)
const myDiv2 = document.createElement("div")
myDiv2.setAttribute("data-name", "BMW")
myDiv2.classList.add("tile")
const myImg21 = document.createElement("img")
myImg21.classList.add("front")
myImg21.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/bmw-logo1.jpg")
myImg21.setAttribute("alt", "BMW")
myDiv2.appendChild(myImg21)
const myImg22 = document.createElement("img")
myImg22.classList.add("back")
myImg22.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg22.setAttribute("alt", "Flip It")
myDiv2.appendChild(myImg22)
const myDiv3 = document.createElement("div")
myDiv3.setAttribute("data-name", "Audi")
myDiv3.classList.add("tile")
const myImg31 = document.createElement("img")
myImg31.classList.add("front")
myImg31.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/audi-logo.jpg")
myImg31.setAttribute("alt", "Audi")
myDiv3.appendChild(myImg31)
const myImg32 = document.createElement("img")
myImg32.classList.add("back")
myImg32.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg32.setAttribute("alt", "Flip It")
myDiv3.appendChild(myImg32)
const myDiv4 = document.createElement("div")
myDiv4.setAttribute("data-name", "Audi")
myDiv4.classList.add("tile")
const myImg41 = document.createElement("img")
myImg41.classList.add("front")
myImg41.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/audi-logo.jpg")
myImg41.setAttribute("alt", "Audi")
myDiv4.appendChild(myImg41)
const myImg42 = document.createElement("img")
myImg42.classList.add("back")
myImg42.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg42.setAttribute("alt", "Flip It")
myDiv4.appendChild(myImg42)
const myDiv5 = document.createElement("div")
myDiv5.setAttribute("data-name", "Aston Martin")
myDiv5.classList.add("tile")
const myImg51 = document.createElement("img")
myImg51.classList.add("front")
myImg51.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/aston-martin-logo2.jpg")
myImg51.setAttribute("alt", "Aston Martin")
myDiv5.appendChild(myImg51)
const myImg52 = document.createElement("img")
myImg52.classList.add("back")
myImg52.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg52.setAttribute("alt", "Flip It")
myDiv5.appendChild(myImg52)
const myDiv6 = document.createElement("div")
myDiv6.setAttribute("data-name", "Aston Martin")
myDiv6.classList.add("tile")
const myImg61 = document.createElement("img")
myImg61.classList.add("front")
myImg61.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/aston-martin-logo2.jpg")
myImg61.setAttribute("alt", "Aston Martin")
myDiv6.appendChild(myImg61)
const myImg62 = document.createElement("img")
myImg62.classList.add("back")
myImg62.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg62.setAttribute("alt", "Flip It")
myDiv6.appendChild(myImg62)
const myDiv7 = document.createElement("div")
myDiv7.setAttribute("data-name", "Bentley")
myDiv7.classList.add("tile")
const myImg71 = document.createElement("img")
myImg71.classList.add("front")
myImg71.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Bentley-Logo.jpg")
myImg71.setAttribute("alt", "Bentley")
myDiv7.appendChild(myImg71)
const myImg72 = document.createElement("img")
myImg72.classList.add("back")
myImg72.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg72.setAttribute("alt", "Flip It")
myDiv7.appendChild(myImg72)
const myDiv8 = document.createElement("div")
myDiv8.setAttribute("data-name", "Bentley")
myDiv8.classList.add("tile")
const myImg81 = document.createElement("img")
myImg81.classList.add("front")
myImg81.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Bentley-Logo.jpg")
myImg81.setAttribute("alt", "Bentley")
myDiv8.appendChild(myImg81)
const myImg82 = document.createElement("img")
myImg82.classList.add("back")
myImg82.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg82.setAttribute("alt", "Flip It")
myDiv8.appendChild(myImg82)
const myDiv9 = document.createElement("div")
myDiv9.setAttribute("data-name", "Renault")
myDiv9.classList.add("tile")
const myImg91 = document.createElement("img")
myImg91.classList.add("front")
myImg91.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/renault-logo.jpg")
myImg91.setAttribute("alt", "Renault")
myDiv9.appendChild(myImg91)
const myImg92 = document.createElement("img")
myImg92.classList.add("back")
myImg92.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg92.setAttribute("alt", "Flip It")
myDiv9.appendChild(myImg92)
const myDiv10 = document.createElement("div")
myDiv10.setAttribute("data-name", "Renault")
myDiv10.classList.add("tile")
const myImg101 = document.createElement("img")
myImg101.classList.add("front")
myImg101.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/renault-logo.jpg")
myImg101.setAttribute("alt", "Renault")
myDiv10.appendChild(myImg101)
const myImg102 = document.createElement("img")
myImg102.classList.add("back")
myImg102.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg102.setAttribute("alt", " Flip It")
myDiv10.appendChild(myImg102)
const myDiv11 = document.createElement("div")
myDiv11.setAttribute("data-name", "Ferrari")
myDiv11.classList.add("tile")
const myImg111 = document.createElement("img")
myImg111.classList.add("front")
myImg111.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/ferrari-logo.jpg")
myImg111.setAttribute("alt", "Ferrari")
myDiv11.appendChild(myImg111)
const myImg112 = document.createElement("img")
myImg112.classList.add("back")
myImg112.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg112.setAttribute("alt", "Flip It")
myDiv11.appendChild(myImg112)
const myDiv12 = document.createElement("div")
myDiv12.setAttribute("data-name", "Ferrari")
myDiv12.classList.add("tile")
const myImg121 = document.createElement("img")
myImg121.classList.add("front")
myImg121.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/ferrari-logo.jpg")
myImg121.setAttribute("alt", "Ferrari")
myDiv12.appendChild(myImg121)
const myImg122 = document.createElement("img")
myImg122.classList.add("back")
myImg122.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg122.setAttribute("alt", "Flip It")
myDiv12.appendChild(myImg122)
const myDiv13 = document.createElement("div")
myDiv13.setAttribute("data-name", "Ford")
myDiv13.classList.add("tile")
const myImg131 = document.createElement("img")
myImg131.classList.add("front")
myImg131.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/ford-logo.jpg")
myImg131.setAttribute("alt", "Ford")
myDiv13.appendChild(myImg131)
const myImg132 = document.createElement("img")
myImg132.classList.add("back")
myImg132.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg132.setAttribute("alt", "Flip It")
myDiv13.appendChild(myImg132)
const myDiv14 = document.createElement("div")
myDiv14.setAttribute("data-name", "Ford")
myDiv14.classList.add("tile")
const myImg141 = document.createElement("img")
myImg141.classList.add("front")
myImg141.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/ford-logo.jpg")
myImg141.setAttribute("alt", "Ford")
myDiv14.appendChild(myImg141)
const myImg142 = document.createElement("img")
myImg142.classList.add("back")
myImg142.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg142.setAttribute("alt", "Flip It")
myDiv14.appendChild(myImg142)
const myDiv15 = document.createElement("div")
myDiv15.setAttribute("data-name", "Honda")
myDiv15.classList.add("tile")
const myImg151 = document.createElement("img")
myImg151.classList.add("front")
myImg151.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/honda-logo.jpg")
myImg151.setAttribute("alt", "Honda")
myDiv15.appendChild(myImg151)
const myImg152 = document.createElement("img")
myImg152.classList.add("back")
myImg152.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg152.setAttribute("alt", "Flip It")
myDiv15.appendChild(myImg152)
const myDiv16 = document.createElement("div")
myDiv16.setAttribute("data-name", "Honda")
myDiv16.classList.add("tile")
const myImg161 = document.createElement("img")
myImg161.classList.add("front")
myImg161.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/honda-logo.jpg")
myImg161.setAttribute("alt", "Honda")
myDiv16.appendChild(myImg161)
const myImg162 = document.createElement("img")
myImg162.classList.add("back")
myImg162.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg162.setAttribute("alt", "Flip It")
myDiv16.appendChild(myImg162)
const myDiv17 = document.createElement("div")
myDiv17.setAttribute("data-name", "Hyundai")
myDiv17.classList.add("tile")
const myImg171 = document.createElement("img")
myImg171.classList.add("front")
myImg171.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/hyundai-logo.jpg")
myImg171.setAttribute("alt", "Hyundai")
myDiv17.appendChild(myImg171)
const myImg172 = document.createElement("img")
myImg172.classList.add("back")
myImg172.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg172.setAttribute("alt", "Flip It")
myDiv17.appendChild(myImg172)
const myDiv18 = document.createElement("div")
myDiv18.setAttribute("data-name", "Hyundai")
myDiv18.classList.add("tile")
const myImg181 = document.createElement("img")
myImg181.classList.add("front")
myImg181.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/hyundai-logo.jpg")
myImg181.setAttribute("alt", "Hyundai")
myDiv18.appendChild(myImg181)
const myImg182 = document.createElement("img")
myImg182.classList.add("back")
myImg182.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg182.setAttribute("alt", "Flip It")
myDiv18.appendChild(myImg182)
const myDiv19 = document.createElement("div")
myDiv19.setAttribute("data-name", "Jaguar")
myDiv19.classList.add("tile")
const myImg191 = document.createElement("img")
myImg191.classList.add("front")
myImg191.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/jaguar-cars-logo1.jpg")
myImg191.setAttribute("alt", "Jaguar")
myDiv19.appendChild(myImg191)
const myImg192 = document.createElement("img")
myImg192.classList.add("back")
myImg192.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg192.setAttribute("alt", "Flip It")
myDiv19.appendChild(myImg192)
const myDiv20 = document.createElement("div")
myDiv20.setAttribute("data-name", "Jaguar")
myDiv20.classList.add("tile")
const myImg201 = document.createElement("img")
myImg201.classList.add("front")
myImg201.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/jaguar-cars-logo1.jpg")
myImg201.setAttribute("alt", "Jaguar")
myDiv20.appendChild(myImg201)
const myImg202 = document.createElement("img")
myImg202.classList.add("back")
myImg202.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg202.setAttribute("alt", "Flip It")
myDiv20.appendChild(myImg202)
const myDiv21 = document.createElement("div")
myDiv21.setAttribute("data-name", "Jeep")
myDiv21.classList.add("tile")
const myImg211 = document.createElement("img")
myImg211.classList.add("front")
myImg211.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Jeep-Logo.jpg")
myImg211.setAttribute("alt", "Jeep")
myDiv21.appendChild(myImg211)
const myImg212 = document.createElement("img")
myImg212.classList.add("back")
myImg212.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg212.setAttribute("alt", "Flip It")
myDiv21.appendChild(myImg212)
const myDiv22 = document.createElement("div")
myDiv22.setAttribute("data-name", "Jeep")
myDiv22.classList.add("tile")
const myImg221 = document.createElement("img")
myImg221.classList.add("front")
myImg221.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Jeep-Logo.jpg")
myImg221.setAttribute("alt", "Jeep")
myDiv22.appendChild(myImg221)
const myImg222 = document.createElement("img")
myImg222.classList.add("back")
myImg222.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg222.setAttribute("alt", "Flip It")
myDiv22.appendChild(myImg222)
const myDiv23 = document.createElement("div")
myDiv23.setAttribute("data-name", "Kia")
myDiv23.classList.add("tile")
const myImg231 = document.createElement("img")
myImg231.classList.add("front")
myImg231.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Kia-Motors-Logo.jpg")
myImg231.setAttribute("alt", "Kia")
myDiv23.appendChild(myImg231)
const myImg232 = document.createElement("img")
myImg232.classList.add("back")
myImg232.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg232.setAttribute("alt", "Flip It")
myDiv23.appendChild(myImg232)
const myDiv24 = document.createElement("div")
myDiv24.setAttribute("data-name", "Kia")
myDiv24.classList.add("tile")
const myImg241 = document.createElement("img")
myImg241.classList.add("front")
myImg241.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Kia-Motors-Logo.jpg")
myImg241.setAttribute("alt", "Kia")
myDiv24.appendChild(myImg241)
const myImg242 = document.createElement("img")
myImg242.classList.add("back")
myImg242.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg242.setAttribute("alt", "Flip It")
myDiv24.appendChild(myImg242)
const myDiv25 = document.createElement("div")
myDiv25.setAttribute("data-name", "Land Rover")
myDiv25.classList.add("tile")
const myImg251 = document.createElement("img")
myImg251.classList.add("front")
myImg251.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/land-rover-logo1.jpg")
myImg251.setAttribute("alt", "Land Rover")
myDiv25.appendChild(myImg251)
const myImg252 = document.createElement("img")
myImg252.classList.add("back")
myImg252.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg252.setAttribute("alt", "Flip It")
myDiv25.appendChild(myImg252)
const myDiv26 = document.createElement("div")
myDiv26.setAttribute("data-name", "Land Rover")
myDiv26.classList.add("tile")
const myImg261 = document.createElement("img")
myImg261.classList.add("front")
myImg261.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/land-rover-logo1.jpg")
myImg261.setAttribute("alt", "Land Rover")
myDiv26.appendChild(myImg261)
const myImg262 = document.createElement("img")
myImg262.classList.add("back")
myImg262.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg262.setAttribute("alt", "Flip It")
myDiv26.appendChild(myImg262)
const myDiv27 = document.createElement("div")
myDiv27.setAttribute("data-name", "Mini")
myDiv27.classList.add("tile")
const myImg271 = document.createElement("img")
myImg271.classList.add("front")
myImg271.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Mini-Car-Logo1.jpg")
myImg271.setAttribute("alt", "Mini")
myDiv27.appendChild(myImg271)
const myImg272 = document.createElement("img")
myImg272.classList.add("back")
myImg272.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg272.setAttribute("alt", "Flip It")
myDiv27.appendChild(myImg272)
const myDiv28 = document.createElement("div")
myDiv28.setAttribute("data-name", "Mini")
myDiv28.classList.add("tile")
const myImg281 = document.createElement("img")
myImg281.classList.add("front")
myImg281.setAttribute("src", "https://s8096.pcdn.co/wp-content/uploads/2014/10/Mini-Car-Logo1.jpg")
myImg281.setAttribute("alt", "Mini")
myDiv28.appendChild(myImg281)
const myImg282 = document.createElement("img")
myImg282.classList.add("back")
myImg282.setAttribute("src", "https://i.ytimg.com/vi/G-8EeVdWBR0/maxresdefault.jpg")
myImg282.setAttribute("alt", "Flip It")
myDiv28.appendChild(myImg282)

mySection.appendChild(myDiv1)
mySection.appendChild(myDiv2)
mySection.appendChild(myDiv3)
mySection.appendChild(myDiv4)
mySection.appendChild(myDiv5)
mySection.appendChild(myDiv6)
mySection.appendChild(myDiv7)
mySection.appendChild(myDiv8)
mySection.appendChild(myDiv9)
mySection.appendChild(myDiv10)
mySection.appendChild(myDiv11)
mySection.appendChild(myDiv12)
mySection.appendChild(myDiv13)
mySection.appendChild(myDiv14)
mySection.appendChild(myDiv15)
mySection.appendChild(myDiv16)
mySection.appendChild(myDiv17)
mySection.appendChild(myDiv18)
mySection.appendChild(myDiv19)
mySection.appendChild(myDiv20)
mySection.appendChild(myDiv21)
mySection.appendChild(myDiv22)
mySection.appendChild(myDiv23)
mySection.appendChild(myDiv24)
mySection.appendChild(myDiv25)
mySection.appendChild(myDiv26)
mySection.appendChild(myDiv27)
mySection.appendChild(myDiv28)
body.appendChild(mySection);

const tiles = document.querySelectorAll('.tile');



let isTileFlipped = false;
let lockGame = false;
let firstTile, secondTile;

function flipTile() {

  if (lockGame) 
  return;

  if (this === firstTile) 
  return;

  this.classList.add('flip');

  if (!isTileFlipped) {
    isTileFlipped = true;
    firstTile = this;
    return;
  }

  secondTile = this;
  checkForMatch();
}

function checkForMatch() {
  let isMatch = firstTile.dataset.name === secondTile.dataset.name;

  if(isMatch){
      disableTiles();
    }else{
      unflipTiles();
    }
}

function disableTiles() {
  firstTile.removeEventListener('click', flipTile);
  secondTile.removeEventListener('click', flipTile);

  resetGame();
}

function unflipTiles() {
  lockGame = true;

  setTimeout(() => {
    firstTile.classList.remove('flip');
    secondTile.classList.remove('flip');

    resetGame();
  }, 1000);
}

 resetGame = () => {
  [isTileFlipped, lockGame] = [false, false];
  [firstTile, secondTile] = [null, null];
}

(function shuffle() {
  tiles.forEach(tile => {
    let position = Math.floor(Math.random() * 14);
    tile.style.order = position;
  });
})();

tiles.forEach(tile => tile.addEventListener('click', flipTile));

